### ISSUE TITLE
Cannot build on Raspbian Buster

### ISSUE THREAD

**Issue by SylvainGarrigues** [Motion-Project/motion-packaging#7]
Adding `set -e -x` to build script, one can see it fails with:
```builddeb.sh: 186: builddeb.sh: ./version.sh: not found```

**Comment by tosiara** [comment]
Resolved in this PR: https://github.com/Motion-Project/motion-packaging/pull/6

**Comment by SylvainGarrigues** [comment]
Doesn't compile even with this fix - the check target fails:

```
/tmp/motion.YAGuFi/motion $ dpkg-buildpackage -us -uc -j4
dpkg-buildpackage: info: source package motion
dpkg-buildpackage: info: source version 4.3.0+git20200122-346ad0d-1
dpkg-buildpackage: info: source distribution buster
dpkg-buildpackage: info: source changed by Sylvain Garrigues <sylvain@sylvaingarrigues.com>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build .
dpkg-source: info: using options from motion/debian/source/options: --extend-diff-ignore=.*
 fakeroot debian/rules clean
dh clean --with autoreconf
   dh_auto_clean
	make -j1 distclean
make[1]: Entering directory '/tmp/motion.YAGuFi/motion'
Making distclean in src
make[2]: Entering directory '/tmp/motion.YAGuFi/motion/src'
test -z "motion" || rm -f motion
rm -f *.o
rm -f raspicam/*.o
rm -f *.tab.c
test -z "" || rm -f
test . = "." || test -z "" || rm -f
rm -f raspicam/.deps/.dirstamp
rm -f raspicam/.dirstamp
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f ./.deps/alg.Po
rm -f ./.deps/conf.Po
rm -f ./.deps/draw.Po
rm -f ./.deps/event.Po
rm -f ./.deps/ffmpeg.Po
rm -f ./.deps/jpegutils.Po
rm -f ./.deps/logger.Po
rm -f ./.deps/md5.Po
rm -f ./.deps/mmalcam.Po
rm -f ./.deps/motion.Po
rm -f ./.deps/netcam.Po
rm -f ./.deps/netcam_ftp.Po
rm -f ./.deps/netcam_http.Po
rm -f ./.deps/netcam_jpeg.Po
rm -f ./.deps/netcam_rtsp.Po
rm -f ./.deps/netcam_wget.Po
rm -f ./.deps/picture.Po
rm -f ./.deps/rotate.Po
rm -f ./.deps/stream.Po
rm -f ./.deps/track.Po
rm -f ./.deps/translate.Po
rm -f ./.deps/video_bktr.Po
rm -f ./.deps/video_common.Po
rm -f ./.deps/video_loopback.Po
rm -f ./.deps/video_v4l2.Po
rm -f ./.deps/webu.Po
rm -f ./.deps/webu_html.Po
rm -f ./.deps/webu_stream.Po
rm -f ./.deps/webu_text.Po
rm -f raspicam/.deps/RaspiCLI.Po
rm -f raspicam/.deps/RaspiCamControl.Po
rm -f Makefile
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion/src'
Making distclean in po
make[2]: Entering directory '/tmp/motion.YAGuFi/motion/po'
rm -f *.insert-header
rm -f remove-potcdate.sed
rm -f stamp-poT
rm -f core core.* motion.po motion.1po motion.2po *.new.po
rm -fr *.o
rm -f Makefile Makefile.in POTFILES *.mo
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion/po'
Making distclean in man
make[2]: Entering directory '/tmp/motion.YAGuFi/motion/man'
test -z "" || rm -f
test . = "." || test -z "" || rm -f
rm -f Makefile
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion/man'
make[2]: Entering directory '/tmp/motion.YAGuFi/motion'
test -z "data/camera1-dist.conf data/camera2-dist.conf data/camera3-dist.conf data/camera4-dist.conf data/motion-dist.conf data/motion.service" || rm -f data/camera1-dist.conf data/camera2-dist.conf data/camera3-dist.conf data/camera4-dist.conf data/motion-dist.conf data/motion.service
test . = "." || test -z "" || rm -f
rm -f config.h stamp-h1
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion'
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
make[1]: Leaving directory '/tmp/motion.YAGuFi/motion'
   dh_autoreconf_clean
   dh_clean
 dpkg-source -b .
dpkg-source: info: using options from motion/debian/source/options: --extend-diff-ignore=.*
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building motion using existing ./motion_4.3.0+git20200122-346ad0d.orig.tar.gz
dpkg-source: info: building motion in motion_4.3.0+git20200122-346ad0d-1.debian.tar.xz
dpkg-source: info: building motion in motion_4.3.0+git20200122-346ad0d-1.dsc
 debian/rules build
dh build --with autoreconf
   dh_update_autotools_config
   dh_autoreconf
Copying file ABOUT-NLS
Copying file config.rpath
Copying file m4/codeset.m4
Copying file m4/extern-inline.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
configure.ac:3: installing './compile'
configure.ac:8: installing './config.guess'
configure.ac:8: installing './config.sub'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
src/Makefile.am: installing './depcomp'
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/tmp/motion.YAGuFi/motion'
dh_auto_configure -- \
  --with-ffmpeg=/usr/lib/arm-linux-gnueabihf \
  --with-mysql-lib=/usr/lib/arm-linux-gnueabihf \
  --with-pgsql-lib=/usr/lib/arm-linux-gnueabihf \
  --without-optimizecpu
	./configure --build=arm-linux-gnueabihf --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/arm-linux-gnueabihf --libexecdir=\${prefix}/lib/arm-linux-gnueabihf --disable-maintainer-mode --disable-dependency-tracking --with-ffmpeg=/usr/lib/arm-linux-gnueabihf --with-mysql-lib=/usr/lib/arm-linux-gnueabihf --with-pgsql-lib=/usr/lib/arm-linux-gnueabihf --without-optimizecpu
configure: WARNING: unrecognized options: --disable-maintainer-mode, --with-mysql-lib, --with-pgsql-lib
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... arm-unknown-linux-gnueabihf
checking host system type... arm-unknown-linux-gnueabihf
checking for a sed that does not truncate output... /bin/sed
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking for ctype.h... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for pkg-config... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking setjmp.h usability... yes
checking setjmp.h presence... yes
checking for setjmp.h... yes
checking jerror.h usability... yes
checking jerror.h presence... yes
checking for jerror.h... yes
checking jpeglib.h usability... yes
checking jpeglib.h presence... yes
checking for jpeglib.h... yes
checking jpg libraries... yes
checking microhttpd.h usability... yes
checking microhttpd.h presence... yes
checking for microhttpd.h... yes
checking libmicrohttpd libraries... yes
checking pthread_np.h usability... no
checking pthread_np.h presence... no
checking for pthread_np.h... no
checking for pthread_setname_np... yes
checking for pthread_getname_np... yes
checking for XSI strerror_r... no
checking dev/bktr/ioctl_meteor.h usability... no
checking dev/bktr/ioctl_meteor.h presence... no
checking for dev/bktr/ioctl_meteor.h... no
checking dev/bktr/ioctl_bt848.h usability... no
checking dev/bktr/ioctl_bt848.h presence... no
checking for dev/bktr/ioctl_bt848.h... no
checking dev/ic/bt8xx.h usability... no
checking dev/ic/bt8xx.h presence... no
checking for dev/ic/bt8xx.h... no
checking linux/videodev2.h usability... yes
checking linux/videodev2.h presence... yes
checking for linux/videodev2.h... yes
checking for webp... yes
checking MMAL pkg-config path... .:/opt/vc/lib/pkgconfig
checking for MMAL... yes
checking FFmpeg pkg-config path... /usr/lib/arm-linux-gnueabihf/lib/pkgconfig:
checking for FFmpeg... yes
checking MariaDB pkg-config path...
checking for MariaDB... yes
checking MySQL pkg-config path...
checking for MySQL... yes
checking PostgreSQL pkg-config path...
checking for PostgreSQL... yes
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
checking for kill... /bin/kill
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating po/Makefile.in
config.status: creating man/Makefile
config.status: creating data/camera1-dist.conf
config.status: creating data/camera2-dist.conf
config.status: creating data/camera3-dist.conf
config.status: creating data/camera4-dist.conf
config.status: creating data/motion-dist.conf
config.status: creating data/motion.service
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
configure: WARNING: unrecognized options: --disable-maintainer-mode, --with-mysql-lib, --with-pgsql-lib

   **************************
      Configure status
      motion 4.3.0+git20200122-346ad0d
   **************************

CFLAGS: -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql

LIBS:  -pthread   -ljpeg -lmicrohttpd -lwebpmux -lwebp -L/opt/vc/lib -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -lvcsm -lvcos -lvchostif  -lavutil -lavformat -lavcodec -lswscale -lavdevice -lmariadb -lpthread -lz -ldl -lm -lgnutls -lmariadb -lpthread -lz -ldl -lm -lgnutls -lpq -lsqlite3

LDFLAGS:


OS                  : linux-gnueabihf
pthread_np          : no
pthread_setname_np  : yes
pthread_getname_np  : yes
XSI error           : no
webp support        : yes
V4L2 support        : yes
BKTR support        : no
MMAL support        : yes
FFmpeg support      : yes
libavformat version : 58.20.100
SQLite3 support     : yes
MYSQL support       : yes
PostgreSQL support  : yes
MariaDB support     : yes

Install prefix:       /usr

make[1]: Leaving directory '/tmp/motion.YAGuFi/motion'
   dh_auto_build
	make -j1
make[1]: Entering directory '/tmp/motion.YAGuFi/motion'
make  all-recursive
make[2]: Entering directory '/tmp/motion.YAGuFi/motion'
Making all in src
make[3]: Entering directory '/tmp/motion.YAGuFi/motion/src'
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o motion.o motion.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o logger.o logger.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o conf.o conf.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o draw.o draw.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o jpegutils.o jpegutils.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o video_loopback.o video_loopback.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o video_v4l2.o video_v4l2.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o video_common.o video_common.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o video_bktr.o video_bktr.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o netcam.o netcam.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o netcam_http.o netcam_http.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o netcam_ftp.o netcam_ftp.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o netcam_jpeg.o netcam_jpeg.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o netcam_wget.o netcam_wget.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o netcam_rtsp.o netcam_rtsp.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o track.o track.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o alg.o alg.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o event.o event.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o picture.o picture.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o rotate.o rotate.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o translate.o translate.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o md5.o md5.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o stream.o stream.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o ffmpeg.o ffmpeg.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o webu.o webu.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o webu_html.o webu_html.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o webu_stream.o webu_stream.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o webu_text.o webu_text.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o mmalcam.o mmalcam.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o raspicam/RaspiCamControl.o raspicam/RaspiCamControl.c
gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -c -o raspicam/RaspiCLI.o raspicam/RaspiCLI.c
gcc -Dsysconfdir=\"/etc/motion\" -DLOCALEDIR=\"/usr/share/locale\" -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql    -o motion motion.o logger.o conf.o draw.o jpegutils.o video_loopback.o video_v4l2.o video_common.o video_bktr.o netcam.o netcam_http.o netcam_ftp.o netcam_jpeg.o netcam_wget.o netcam_rtsp.o track.o alg.o event.o picture.o rotate.o translate.o md5.o stream.o ffmpeg.o webu.o webu_html.o webu_stream.o webu_text.o mmalcam.o raspicam/RaspiCamControl.o raspicam/RaspiCLI.o  -pthread   -ljpeg -lmicrohttpd -lwebpmux -lwebp -L/opt/vc/lib -lmmal -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host -lvcsm -lvcos -lvchostif  -lavutil -lavformat -lavcodec -lswscale -lavdevice -lmariadb -lpthread -lz -ldl -lm -lgnutls -lmariadb -lpthread -lz -ldl -lm -lgnutls -lpq -lsqlite3
make[3]: Leaving directory '/tmp/motion.YAGuFi/motion/src'
Making all in po
make[3]: Entering directory '/tmp/motion.YAGuFi/motion/po'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/motion.YAGuFi/motion/po'
Making all in man
make[3]: Entering directory '/tmp/motion.YAGuFi/motion/man'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/motion.YAGuFi/motion/man'
make[3]: Entering directory '/tmp/motion.YAGuFi/motion'
make[3]: Leaving directory '/tmp/motion.YAGuFi/motion'
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion'
make[1]: Leaving directory '/tmp/motion.YAGuFi/motion'
   dh_auto_test
	make -j1 check VERBOSE=1
make[1]: Entering directory '/tmp/motion.YAGuFi/motion'
Making check in src
make[2]: Entering directory '/tmp/motion.YAGuFi/motion/src'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion/src'
Making check in po
make[2]: Entering directory '/tmp/motion.YAGuFi/motion/po'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion/po'
Making check in man
make[2]: Entering directory '/tmp/motion.YAGuFi/motion/man'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion/man'
make[2]: Entering directory '/tmp/motion.YAGuFi/motion'
make[2]: Leaving directory '/tmp/motion.YAGuFi/motion'
./configure --with-prototype-flags                   && make clean && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/motion.YAGuFi/motion':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[1]: *** [Makefile:992: check] Error 77
make[1]: Leaving directory '/tmp/motion.YAGuFi/motion'
dh_auto_test: make -j1 check VERBOSE=1 returned exit code 2
make: *** [debian/rules:10: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by SylvainGarrigues** [comment]
Manually running `./configure --with-prototype-flags` does work though

**Comment by SylvainGarrigues** [comment]
This is the error in config.log:

```
configure:3159: checking whether the C compiler works
configure:3181: gcc -g -O2 -fdebug-prefix-map=/tmp/motion.YAGuFi/motion=. -fstack-protector-strong -Wformat -Werror=format-security -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/mariadb -I/usr/include/mariadb/.. -I/usr/include/postgresql  -D_THREAD_SAFE    -I/usr/include/p11-kit-1  -Irasppicam -I/opt/vc/include -I/usr/include/arm-linux-gnueabihf -W -Werror -Wall -Wextra -Wformat -Wshadow -Wpointer-arith -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wredundant-decls -Wno-long-long -ggdb -g3 -Wdate-time -D_FORTIFY_SOURCE=2  conftest.c  >&5
conftest.c:13:1: error: function declaration isn't a prototype [-Werror=strict-prototypes]
 main ()
 ^~~~
cc1: all warnings being treated as errors
configure:3185: $? = 1
configure:3223: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "motion"
| #define PACKAGE_TARNAME "motion"
| #define PACKAGE_VERSION "4.3.0+git20200122-346ad0d"
| #define PACKAGE_STRING "motion 4.3.0+git20200122-346ad0d"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "motion"
| #define VERSION "4.3.0+git20200122-346ad0d"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3228: error: in `/tmp/motion.YAGuFi/motion':
configure:3230: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by tosiara** [comment]
Could you please be more specific what is your issue?
I dont have Rasperry, but I'm able to build motion using Debian Buster after applying PR#6:

![image](https://user-images.githubusercontent.com/3600973/74736391-474dbd00-525b-11ea-8641-d2f10eaff0fe.png)

**Comment by SylvainGarrigues** [comment]
The issue is `sh builddeb.sh` fails with the error above _on a RPI3 with latest Rasbian Buster_ even after applying your merge request. 

My conclusion is that the configure script fails because `-Werror=strict-prototypes` in CFLAGS. I don't know why it works on a x86/amd64 Debian.

**Comment by SylvainGarrigues** [comment]
After further investigation, the issue is in the test suite (the `check` part of `Makefile.am`). If I disable the test suite by setting `DEB_BUILD_OPTIONS=nocheck` in the environment before executing `builddeb.sh`, the build completes.

The produced `configure` script simply doesn't like the `--with-prototype-flags` it is given by the generated `Makefile` from `Makefile.am`.

**Comment by kristofejro** [comment]
I have exactly the same problem.

After
`git clone https://github.com/Motion-Project/motion-packaging.git`

and running builddeb.sh I have error:

```
Usage:    builddeb.sh name email <optional branch>
Name:     Name to use for deb package must not include spaces
Email:    Email address to use for deb package
Branch:   The git branch name of Motion to build (If none specified, uses master)
Install:  Install required packages
Arch:     Architecture


Using Username: AdhocBuild, User Email: AdhocBuild@nowhere.com, Git Branch: master, Install Pkgs: N, Arch: armv7l

All packages installed
Cloning into 'motion'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 6912 (delta 17), reused 6 (delta 2), pack-reused 6884
Receiving objects: 100% (6912/6912), 6.01 MiB | 5.76 MiB/s, done.
Resolving deltas: 100% (5164/5164), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
./builddeb.sh: 184: ./builddeb.sh: ./version.sh: not found
Already on 'master'
Your branch is up to date with 'origin/master'.
Building package....
The deb packages and build logs have been created and placed into /tmp/motion/motion-packaging
```

Platform is Raspberry Pi 3B+

**Comment by tosiara** [comment]
Once again, resolved in this PR: https://github.com/Motion-Project/motion-packaging/pull/6

**Comment by SylvainGarrigues** [comment]
Please see my last comment. https://github.com/Motion-Project/motion-packaging/pull/6 fixes the `./builddeb.sh: 184: ./builddeb.sh: ./version.sh: not found` error: the build continues after that but in the end it still fails with an error. 

Like I said, the error is triggered in the testing phase, which is not mandatory and can be skipped with `DEB_BUILD_OPTIONS=nocheck` in the environment before building.

I don't have time to provide a pull request, but like I said in https://github.com/Motion-Project/motion-packaging/issues/7#issuecomment-587560624, to properly fix the `check` target from `Makefile.am`, one would need to understand why the `configure` program tests the GCC compiler by trying to compile a C file with a `main` function declared as `int main() {}`:  this fails to compile because `CFLAGS` has missing prototypes treated as error (`-Werror=strict-prototypes`) from the `check` target. `main` should be `int main(int argc, char *argv[]) {}`.

**Comment by tosiara** [comment]
@SylvainGarrigues please create a new issue for this one. Do not mix multiple issues into one. The issue https://github.com/Motion-Project/motion-packaging/issues/7 has been started as related to `version.sh not found`, lets keep it consistent. If you can confirm that https://github.com/Motion-Project/motion-packaging/pull/6 resolves your original issue - lets close this one and start a separate for any else issues you have
As you can see other users are confused and keep commenting "I have the same issue". So please close this issue and start a separate one. Thank you

**Comment by SylvainGarrigues** [comment]
Solved in https://github.com/Motion-Project/motion-packaging/pull/6
